### ISSUE TITLE
Image widget for core

### ISSUE THREAD

**Issue by paaljoachim** [blazersix/simple-image-widget#12]
Hey Brady

I happen to come across this trac ticket:
https://core.trac.wordpress.org/ticket/32417

Since you have a widget plugin in the repo today I am thinking that perhaps it would be interesting for you to also help with the image (media) widget being slowly created for core.

Have a great day!

**Comment by bradyvercher** [comment]
Thanks for pinging me about this @paaljoachim. I'm watching that ticket and will help out however I can.

**Comment by paaljoachim** [comment]
Great!
