### ISSUE TITLE
Change title to "advanced image"

### ISSUE THREAD

**Issue by frietboer** [blazersix/simple-image-widget#18]
Great plugin, we use this on our multisite and it works great. Only issue is now with the advent of the latest Wordpress version, there is a new image widget. 

I know the plugin is called "simple image widget" but it is more advanced that the WP version. So might it be a good idea to change the title? In our case "advanced image" would be best.

**Comment by bradyvercher** [comment]
Thanks for the suggestion, @frietboer. I think the core widget can do just about everything this one does (aside from custom templates and link searching), but I find core's a little more difficult to use. I think I'll go with your suggestion to update the title, but call it `Image (Simple)` instead.
